// Shared ISO-3166 alpha-2 country list — used for "Nationality" and
// "Country of residence" selects (profile + checkout). GCC + most-common
// source markets first, then alphabetical. Single source of truth so the
// profile and checkout selects never drift apart.
export const COUNTRIES: ReadonlyArray<readonly [string, string]> = [
  // GCC + regional first (most common customers)
  ['AE', 'United Arab Emirates'],
  ['SA', 'Saudi Arabia'],
  ['QA', 'Qatar'],
  ['KW', 'Kuwait'],
  ['BH', 'Bahrain'],
  ['OM', 'Oman'],
  // High-volume source markets
  ['IN', 'India'],
  ['PK', 'Pakistan'],
  ['PH', 'Philippines'],
  ['EG', 'Egypt'],
  ['JO', 'Jordan'],
  ['LB', 'Lebanon'],
  ['GB', 'United Kingdom'],
  ['US', 'United States'],
  // Alphabetical rest
  ['AF', 'Afghanistan'],
  ['AL', 'Albania'],
  ['DZ', 'Algeria'],
  ['AR', 'Argentina'],
  ['AM', 'Armenia'],
  ['AU', 'Australia'],
  ['AT', 'Austria'],
  ['AZ', 'Azerbaijan'],
  ['BD', 'Bangladesh'],
  ['BY', 'Belarus'],
  ['BE', 'Belgium'],
  ['BR', 'Brazil'],
  ['BG', 'Bulgaria'],
  ['CA', 'Canada'],
  ['CL', 'Chile'],
  ['CN', 'China'],
  ['CO', 'Colombia'],
  ['HR', 'Croatia'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czechia'],
  ['DK', 'Denmark'],
  ['ET', 'Ethiopia'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['GE', 'Georgia'],
  ['DE', 'Germany'],
  ['GH', 'Ghana'],
  ['GR', 'Greece'],
  ['HU', 'Hungary'],
  ['IS', 'Iceland'],
  ['ID', 'Indonesia'],
  ['IR', 'Iran'],
  ['IQ', 'Iraq'],
  ['IE', 'Ireland'],
  ['IT', 'Italy'],
  ['JP', 'Japan'],
  ['KZ', 'Kazakhstan'],
  ['KE', 'Kenya'],
  ['KR', 'South Korea'],
  ['KG', 'Kyrgyzstan'],
  ['LV', 'Latvia'],
  ['LY', 'Libya'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['MY', 'Malaysia'],
  ['MV', 'Maldives'],
  ['MT', 'Malta'],
  ['MU', 'Mauritius'],
  ['MX', 'Mexico'],
  ['MD', 'Moldova'],
  ['MN', 'Mongolia'],
  ['MA', 'Morocco'],
  ['MM', 'Myanmar'],
  ['NP', 'Nepal'],
  ['NL', 'Netherlands'],
  ['NZ', 'New Zealand'],
  ['NG', 'Nigeria'],
  ['MK', 'North Macedonia'],
  ['NO', 'Norway'],
  ['PS', 'Palestine'],
  ['PE', 'Peru'],
  ['PL', 'Poland'],
  ['PT', 'Portugal'],
  ['RO', 'Romania'],
  ['RU', 'Russia'],
  ['RW', 'Rwanda'],
  ['RS', 'Serbia'],
  ['SG', 'Singapore'],
  ['SK', 'Slovakia'],
  ['SI', 'Slovenia'],
  ['SO', 'Somalia'],
  ['ZA', 'South Africa'],
  ['ES', 'Spain'],
  ['LK', 'Sri Lanka'],
  ['SD', 'Sudan'],
  ['SE', 'Sweden'],
  ['CH', 'Switzerland'],
  ['SY', 'Syria'],
  ['TW', 'Taiwan'],
  ['TJ', 'Tajikistan'],
  ['TZ', 'Tanzania'],
  ['TH', 'Thailand'],
  ['TN', 'Tunisia'],
  ['TR', 'Türkiye'],
  ['TM', 'Turkmenistan'],
  ['UG', 'Uganda'],
  ['UA', 'Ukraine'],
  ['UY', 'Uruguay'],
  ['UZ', 'Uzbekistan'],
  ['VN', 'Vietnam'],
  ['YE', 'Yemen'],
  ['ZW', 'Zimbabwe'],
] as const

export function isCountryCode(v: string): boolean {
  return COUNTRIES.some(([code]) => code === v)
}
